function( _split_defs _defs _form _out_var)
    string(REPLACE "|" ";" _split_defs "${_defs}")
    foreach (item IN LISTS _defs)
        string(REPLACE "=" ";" parts "${item}")
        list(GET parts 0 key)
        list(GET parts 1 value)
        if (_form STREQUAL "SET")
            string(CONFIGURE "${value}" CONFIGURED_VALUE @ONLY)
            list(APPEND _tmp "set(${key} \"${CONFIGURED_VALUE}\")")
        else ()
            list(APPEND _tmp "unset(${key})")
        endif ()
    endforeach ()
    set(${_out_var} ${_tmp} PARENT_SCOPE)
endfunction ()

function( write_pre_test _target_file _defs TEST_ROOT)
    if (_defs AND NOT _defs STREQUAL "NONE")
        _split_defs(${_defs} "SET" _pre_def_str)
        file(APPEND ${SETUP_CMAKELISTS_FILE} "${_pre_def_str}\n")
    endif ()
endfunction ()

function( write_post_test _target_file _defs)
    if (_defs AND NOT _defs STREQUAL "NONE")
        _split_defs(${_defs} "UNSET" _post_def_str)
        file(APPEND ${SETUP_CMAKELISTS_FILE} "${_post_def_str}\n")
    endif ()
endfunction ()

